<template>
  <div class="loadingio-spinner-heart-mra3q3k139">
    <div class="ldio-rj3b8wncwz">
      <div><div></div></div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style scoped>
@keyframes ldio-rj3b8wncwz {
  0% {
    transform: scale(0.85);
  }
  5% {
    transform: scale(1);
  }
  39% {
    transform: scale(0.75);
  }
  45% {
    transform: scale(0.9);
  }
  60% {
    transform: scale(0.85);
  }
  100% {
    transform: scale(0.8);
  }
}
.ldio-rj3b8wncwz > div {
  animation: ldio-rj3b8wncwz 1s infinite cubic-bezier(0.215, 0.61, 0.355, 1);
  transform-origin: 100px 100px;
}
.ldio-rj3b8wncwz > div div {
  top: 65px;
  left: 50px;
  position: absolute;
  width: 100px;
  height: 100px;
  background: #93dbe9;
  transform: rotate(45deg);
}
.ldio-rj3b8wncwz > div div:after,
.ldio-rj3b8wncwz > div div:before {
  content: " ";
  position: absolute;
  display: block;
  width: 100px;
  height: 100px;
  background: #93dbe9;
}
.ldio-rj3b8wncwz > div div:before {
  left: -65px;
  border-radius: 50% 0 0 50%;
}
.ldio-rj3b8wncwz > div div:after {
  top: -65px;
  border-radius: 50% 50% 0 0;
}
.loadingio-spinner-heart-mra3q3k139 {
  width: 300px;
  height: 300px;
  display: inline-block;
  overflow: hidden;
  background: none;
  position: absolute;
  left: 950px;
  top: 300px;
}
.ldio-rj3b8wncwz {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-rj3b8wncwz div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
